<?php

use Illuminate\Database\Seeder;

class StatsOffenseTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('stats_offense')->insert([
            [
                'player_id' => 1,
                'game_id' => 1,
                'inn' => 8.0,
                'pa' => 3,
                'ab' => 3,
                'r' => 1,
                'h' => 2,
                '2b' => 0,
                '3b' => 0,
                'hr' => 0,
                'rbi' => 0,
                'sb' => 1,
                'cs' => 0,
                'bb' => 0,
                'so' => 0,
                'gdp' => 0,
                'hbp' => 0,
                'sh' => 0,
                'sf' => 0,
                'ibb' => 0
            ],
            [
                'player_id' => 2,
                'game_id' => 1,
                'inn' => 8.0,
                'pa' => 3,
                'ab' => 3,
                'r' => 0,
                'h' => 0,
                '2b' => 0,
                '3b' => 0,
                'hr' => 0,
                'rbi' => 0,
                'sb' => 0,
                'cs' => 0,
                'bb' => 0,
                'so' => 1,
                'gdp' => 0,
                'hbp' => 0,
                'sh' => 0,
                'sf' => 0,
                'ibb' => 0
            ],
            [
                'player_id' => 3,
                'game_id' => 1,
                'inn' => 8.0,
                'pa' => 3,
                'ab' => 2,
                'r' => 0,
                'h' => 0,
                '2b' => 0,
                '3b' => 0,
                'hr' => 0,
                'rbi' => 0,
                'sb' => 0,
                'cs' => 0,
                'bb' => 0,
                'so' => 0,
                'gdp' => 0,
                'hbp' => 0,
                'sh' => 1,
                'sf' => 0,
                'ibb' => 0
            ],
            [
                'player_id' => 4,
                'game_id' => 1,
                'inn' => 8.0,
                'pa' => 3,
                'ab' => 3,
                'r' => 0,
                'h' => 0,
                '2b' => 0,
                '3b' => 0,
                'hr' => 0,
                'rbi' => 0,
                'sb' => 0,
                'cs' => 0,
                'bb' => 0,
                'so' => 2,
                'gdp' => 0,
                'hbp' => 0,
                'sh' => 0,
                'sf' => 0,
                'ibb' => 0
            ],
            [
                'player_id' => 5,
                'game_id' => 1,
                'inn' => 7.0,
                'pa' => 2,
                'ab' => 2,
                'r' => 1,
                'h' => 1,
                '2b' => 0,
                '3b' => 0,
                'hr' => 1,
                'rbi' => 3,
                'sb' => 0,
                'cs' => 0,
                'bb' => 0,
                'so' => 1,
                'gdp' => 0,
                'hbp' => 0,
                'sh' => 0,
                'sf' => 0,
                'ibb' => 0
            ],
            [
                'player_id' => 6,
                'game_id' => 1,
                'inn' => 8.0,
                'pa' => 3,
                'ab' => 1,
                'r' => 0,
                'h' => 0,
                '2b' => 0,
                '3b' => 0,
                'hr' => 0,
                'rbi' => 0,
                'sb' => 1,
                'cs' => 0,
                'bb' => 2,
                'so' => 0,
                'gdp' => 0,
                'hbp' => 0,
                'sh' => 0,
                'sf' => 0,
                'ibb' => 0
            ],
            [
                'player_id' => 7,
                'game_id' => 1,
                'inn' => 8.0,
                'pa' => 2,
                'ab' => 2,
                'r' => 0,
                'h' => 0,
                '2b' => 0,
                '3b' => 0,
                'hr' => 0,
                'rbi' => 0,
                'sb' => 0,
                'cs' => 0,
                'bb' => 0,
                'so' => 0,
                'gdp' => 0,
                'hbp' => 0,
                'sh' => 0,
                'sf' => 0,
                'ibb' => 0
            ],
            [
                'player_id' => 8,
                'game_id' => 1,
                'inn' => 8.0,
                'pa' => 3,
                'ab' => 2,
                'r' => 0,
                'h' => 0,
                '2b' => 0,
                '3b' => 0,
                'hr' => 0,
                'rbi' => 1,
                'sb' => 0,
                'cs' => 0,
                'bb' => 0,
                'so' => 0,
                'gdp' => 0,
                'hbp' => 0,
                'sh' => 0,
                'sf' => 1,
                'ibb' => 0
            ],
            [
                'player_id' => 9,
                'game_id' => 1,
                'inn' => 8.0,
                'pa' => 3,
                'ab' => 2,
                'r' => 0,
                'h' => 1,
                '2b' => 0,
                '3b' => 0,
                'hr' => 0,
                'rbi' => 0,
                'sb' => 0,
                'cs' => 0,
                'bb' => 1,
                'so' => 1,
                'gdp' => 0,
                'hbp' => 0,
                'sh' => 0,
                'sf' => 0,
                'ibb' => 0
            ],
            [
                'player_id' => 10,
                'game_id' => 1,
                'inn' => 8.0,
                'pa' => 3,
                'ab' => 3,
                'r' => 1,
                'h' => 0,
                '2b' => 1,
                '3b' => 0,
                'hr' => 0,
                'rbi' => 0,
                'sb' => 0,
                'cs' => 0,
                'bb' => 0,
                'so' => 0,
                'gdp' => 0,
                'hbp' => 0,
                'sh' => 0,
                'sf' => 0,
                'ibb' => 0
            ],
            [
                'player_id' => 12,
                'game_id' => 1,
                'inn' => 1.0,
                'pa' => 1,
                'ab' => 0,
                'r' => 0,
                'h' => 0,
                '2b' => 0,
                '3b' => 0,
                'hr' => 0,
                'rbi' => 0,
                'sb' => 0,
                'cs' => 0,
                'bb' => 0,
                'so' => 0,
                'gdp' => 0,
                'hbp' => 1,
                'sh' => 0,
                'sf' => 0,
                'ibb' => 0
            ],
            [
                'player_id' => 13,
                'game_id' => 1,
                'inn' => 1.0,
                'pa' => 1,
                'ab' => 1,
                'r' => 0,
                'h' => 0,
                '2b' => 0,
                '3b' => 0,
                'hr' => 0,
                'rbi' => 0,
                'sb' => 0,
                'cs' => 0,
                'bb' => 0,
                'so' => 0,
                'gdp' => 0,
                'hbp' => 0,
                'sh' => 0,
                'sf' => 0,
                'ibb' => 0
            ],
            [
                'player_id' => 14,
                'game_id' => 1,
                'inn' => 8.0,
                'pa' => 4,
                'ab' => 4,
                'r' => 1,
                'h' => 2,
                '2b' => 0,
                '3b' => 0,
                'hr' => 0,
                'rbi' => 0,
                'sb' => 0,
                'cs' => 0,
                'bb' => 0,
                'so' => 0,
                'gdp' => 0,
                'hbp' => 1,
                'sh' => 0,
                'sf' => 0,
                'ibb' => 0
            ],
            [
                'player_id' => 15,
                'game_id' => 1,
                'inn' => 8.0,
                'pa' => 4,
                'ab' => 4,
                'r' => 0,
                'h' => 2,
                '2b' => 0,
                '3b' => 0,
                'hr' => 0,
                'rbi' => 0,
                'sb' => 0,
                'cs' => 0,
                'bb' => 0,
                'so' => 1,
                'gdp' => 0,
                'hbp' => 0,
                'sh' => 0,
                'sf' => 0,
                'ibb' => 0
            ],
            [
                'player_id' => 16,
                'game_id' => 1,
                'inn' => 8.0,
                'pa' => 4,
                'ab' => 4,
                'r' => 0,
                'h' => 1,
                '2b' => 0,
                '3b' => 0,
                'hr' => 0,
                'rbi' => 0,
                'sb' => 0,
                'cs' => 0,
                'bb' => 0,
                'so' => 1,
                'gdp' => 0,
                'hbp' => 0,
                'sh' => 0,
                'sf' => 0,
                'ibb' => 0
            ],
            [
                'player_id' => 17,
                'game_id' => 1,
                'inn' => 7.0,
                'pa' => 3,
                'ab' => 3,
                'r' => 0,
                'h' => 0,
                '2b' => 0,
                '3b' => 0,
                'hr' => 0,
                'rbi' => 0,
                'sb' => 0,
                'cs' => 0,
                'bb' => 0,
                'so' => 1,
                'gdp' => 0,
                'hbp' => 0,
                'sh' => 0,
                'sf' => 0,
                'ibb' => 0
            ],
            [
                'player_id' => 18,
                'game_id' => 1,
                'inn' => 8.0,
                'pa' => 4,
                'ab' => 4,
                'r' => 0,
                'h' => 0,
                '2b' => 0,
                '3b' => 0,
                'hr' => 0,
                'rbi' => 0,
                'sb' => 0,
                'cs' => 0,
                'bb' => 0,
                'so' => 2,
                'gdp' => 0,
                'hbp' => 0,
                'sh' => 0,
                'sf' => 0,
                'ibb' => 0
            ],
            [
                'player_id' => 19,
                'game_id' => 1,
                'inn' => 4.0,
                'pa' => 2,
                'ab' => 2,
                'r' => 0,
                'h' => 0,
                '2b' => 0,
                '3b' => 0,
                'hr' => 0,
                'rbi' => 0,
                'sb' => 0,
                'cs' => 0,
                'bb' => 0,
                'so' => 1,
                'gdp' => 0,
                'hbp' => 0,
                'sh' => 0,
                'sf' => 0,
                'ibb' => 0
            ],
            [
                'player_id' => 20,
                'game_id' => 1,
                'inn' => 8.0,
                'pa' => 4,
                'ab' => 4,
                'r' => 0,
                'h' => 3,
                '2b' => 0,
                '3b' => 0,
                'hr' => 0,
                'rbi' => 1,
                'sb' => 0,
                'cs' => 0,
                'bb' => 0,
                'so' => 1,
                'gdp' => 0,
                'hbp' => 0,
                'sh' => 0,
                'sf' => 0,
                'ibb' => 0
            ],
            [
                'player_id' => 21,
                'game_id' => 1,
                'inn' => 8.0,
                'pa' => 3,
                'ab' => 3,
                'r' => 0,
                'h' => 0,
                '2b' => 0,
                '3b' => 0,
                'hr' => 0,
                'rbi' => 0,
                'sb' => 0,
                'cs' => 0,
                'bb' => 0,
                'so' => 1,
                'gdp' => 0,
                'hbp' => 0,
                'sh' => 0,
                'sf' => 0,
                'ibb' => 0
            ]
        ]);
    }
}
