<?php

use Illuminate\Database\Seeder;

class StatsDefenseTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('stats_defense')->insert([
            [
                'player_id' => 1,
                'game_id' => 1,
                'gs' => 1,
                'inn' => 8.0,
                'ch' => 2,
                'po' => 2,
                'a' => 8,
                'e' => 0,
                'dp' => 2,
                'pb' => 0,
                'wp' => 0,
                'sb' => 0,
                'cs' => 0,
                'pof' => 0
            ],
            [
                'player_id' => 2,
                'game_id' => 1,
                'gs' => 1,
                'inn' => 8.0,
                'ch' => 0,
                'po' => 0,
                'a' => 0,
                'e' => 0,
                'dp' => 0,
                'pb' => 0,
                'wp' => 0,
                'sb' => 0,
                'cs' => 1,
                'pof' => 0
            ],
            [
                'player_id' => 3,
                'game_id' => 1,
                'gs' => 1,
                'inn' => 8.0,
                'ch' => 4,
                'po' => 4,
                'a' => 2,
                'e' => 0,
                'dp' => 2,
                'pb' => 0,
                'wp' => 0,
                'sb' => 0,
                'cs' => 0,
                'pof' => 0
            ],
            [
                'player_id' => 5,
                'game_id' => 1,
                'gs' => 1,
                'inn' => 7.0,
                'ch' => 2,
                'po' => 2,
                'a' => 0,
                'e' => 0,
                'dp' => 0,
                'pb' => 0,
                'wp' => 0,
                'sb' => 0,
                'cs' => 0,
                'pof' => 0
            ],
            [
                'player_id' => 6,
                'game_id' => 1,
                'gs' => 1,
                'inn' => 8.0,
                'ch' => 2,
                'po' => 2,
                'a' => 0,
                'e' => 0,
                'dp' => 0,
                'pb' => 0,
                'wp' => 0,
                'sb' => 0,
                'cs' => 0,
                'pof' => 0
            ],
            [
                'player_id' => 7,
                'game_id' => 1,
                'gs' => 1,
                'inn' => 8.0,
                'ch' => 2,
                'po' => 2,
                'a' => 0,
                'e' => 0,
                'dp' => 2,
                'pb' => 0,
                'wp' => 0,
                'sb' => 0,
                'cs' => 0,
                'pof' => 0
            ],
            [
                'player_id' => 8,
                'game_id' => 1,
                'gs' => 1,
                'inn' => 8.0,
                'ch' => 2,
                'po' => 2,
                'a' => 0,
                'e' => 0,
                'dp' => 0,
                'pb' => 0,
                'wp' => 0,
                'sb' => 0,
                'cs' => 0,
                'pof' => 0
            ],
            [
                'player_id' => 9,
                'game_id' => 1,
                'gs' => 1,
                'inn' => 8.0,
                'ch' => 2,
                'po' => 2,
                'a' => 0,
                'e' => 0,
                'dp' => 0,
                'pb' => 0,
                'wp' => 0,
                'sb' => 0,
                'cs' => 0,
                'pof' => 0
            ],
            [
                'player_id' => 10,
                'game_id' => 1,
                'gs' => 1,
                'inn' => 8.0,
                'ch' => 1,
                'po' => 1,
                'a' => 0,
                'e' => 0,
                'dp' => 0,
                'pb' => 0,
                'wp' => 0,
                'sb' => 0,
                'cs' => 0,
                'pof' => 0
            ],
            [
                'player_id' => 11,
                'game_id' => 1,
                'gs' => 1,
                'inn' => 8.0,
                'ch' => 1,
                'po' => 1,
                'a' => 0,
                'e' => 0,
                'dp' => 0,
                'pb' => 0,
                'wp' => 0,
                'sb' => 0,
                'cs' => 0,
                'pof' => 0
            ],
            [
                'player_id' => 13,
                'game_id' => 1,
                'gs' => 0,
                'inn' => 1.0,
                'ch' => 0,
                'po' => 0,
                'a' => 0,
                'e' => 0,
                'dp' => 0,
                'pb' => 0,
                'wp' => 0,
                'sb' => 0,
                'cs' => 0,
                'pof' => 0
            ],
            [
                'player_id' => 14,
                'game_id' => 1,
                'gs' => 1,
                'inn' => 8.0,
                'ch' => 0,
                'po' => 0,
                'a' => 0,
                'e' => 0,
                'dp' => 0,
                'pb' => 0,
                'wp' => 0,
                'sb' => 0,
                'cs' => 0,
                'pof' => 0
            ],
            [
                'player_id' => 15,
                'game_id' => 1,
                'gs' => 1,
                'inn' => 8.0,
                'ch' => 0,
                'po' => 0,
                'a' => 0,
                'e' => 0,
                'dp' => 0,
                'pb' => 0,
                'wp' => 0,
                'sb' => 0,
                'cs' => 0,
                'pof' => 0
            ],
            [
                'player_id' => 16,
                'game_id' => 1,
                'gs' => 1,
                'inn' => 8.0,
                'ch' => 0,
                'po' => 0,
                'a' => 0,
                'e' => 0,
                'dp' => 0,
                'pb' => 0,
                'wp' => 0,
                'sb' => 0,
                'cs' => 0,
                'pof' => 0
            ],
            [
                'player_id' => 17,
                'game_id' => 1,
                'gs' => 1,
                'inn' => 7.0,
                'ch' => 0,
                'po' => 0,
                'a' => 0,
                'e' => 0,
                'dp' => 0,
                'pb' => 0,
                'wp' => 0,
                'sb' => 0,
                'cs' => 0,
                'pof' => 0
            ],
            [
                'player_id' => 18,
                'game_id' => 1,
                'gs' => 1,
                'inn' => 8.0,
                'ch' => 0,
                'po' => 0,
                'a' => 0,
                'e' => 0,
                'dp' => 0,
                'pb' => 0,
                'wp' => 0,
                'sb' => 0,
                'cs' => 0,
                'pof' => 0
            ],
            [
                'player_id' => 19,
                'game_id' => 1,
                'gs' => 1,
                'inn' => 4.0,
                'ch' => 0,
                'po' => 0,
                'a' => 0,
                'e' => 0,
                'dp' => 0,
                'pb' => 0,
                'wp' => 0,
                'sb' => 0,
                'cs' => 0,
                'pof' => 0
            ],
            [
                'player_id' => 21,
                'game_id' => 1,
                'gs' => 1,
                'inn' => 4.0,
                'ch' => 0,
                'po' => 0,
                'a' => 0,
                'e' => 0,
                'dp' => 0,
                'pb' => 0,
                'wp' => 0,
                'sb' => 0,
                'cs' => 0,
                'pof' => 0
            ],
            [
                'player_id' => 22,
                'game_id' => 1,
                'gs' => 0,
                'inn' => 3.0,
                'ch' => 0,
                'po' => 0,
                'a' => 0,
                'e' => 0,
                'dp' => 0,
                'pb' => 0,
                'wp' => 0,
                'sb' => 0,
                'cs' => 0,
                'pof' => 0
            ],
            [
                'player_id' => 23,
                'game_id' => 1,
                'gs' => 0,
                'inn' => 0.1,
                'ch' => 0,
                'po' => 0,
                'a' => 0,
                'e' => 0,
                'dp' => 0,
                'pb' => 0,
                'wp' => 0,
                'sb' => 0,
                'cs' => 0,
                'pof' => 0
            ]
        ]);
    }
}
